services:
  bookstore:
    build: .
    restart: always
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http:/localhost:5000/books"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  db:
    image: postgres:17
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/bookstore.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      bookstore:
        condition: service_healthy

volumes:
  pg_data:
